### ISSUE TITLE
Determine Why Kraken Nodes Are Not Starting (Failing Readiness)

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#701] opened 2017-08-02 18:09 UTC
CI failures due to node readiness failures is getting to be a problem.
We need to know why some nodes are not starting, or taking too long to start.

**Comment by davidewatson** [comment] 2017-08-02 22:43
At the very least we have some timing issues.

> [aws] FAILED - RETRYING: Wait for api server response before continuing (26 retries left).

![screen shot 2017-08-02 at 3 41 28 pm](https://user-images.githubusercontent.com/11819015/28898149-30a83fe8-7799-11e7-9491-ef3856d397c8.png)

**Comment by davidewatson** [comment] 2017-08-02 22:52
Another thing to note, the master nodes ASG has always depended on the etcd module. However, now that we wait for etcd to be healthy before creating the master ASG, we should expect to wait, at least the average master instance type startup type, longer.

**Comment by alejandroEsc** [comment] 2017-08-03 02:31
So comcast today they were trying to bring up a node with t2.medium's and t2.large's for both etcd and master nodes. Readiness failed here, very high level investigation showed that, consistently, one of the master nodes would fail due to some connection/networking error. Eventually, unclear how long the node would be able to report in, here i suspect we may be dealing with t2 bursting, but not sure.

**Comment by davidewatson** [comment] 2017-08-03 03:17
@alejandroEsc: Can you reproduce the issue with the new default m4.medium etcd instance type? Alternatively, if you have logs, check the `ansible/roles/kraken.provider/kraken.provider.aws : debug` task. When I have seen readiness timeout today I have also noticed that etcd did fully come up:

```
                "stdout": "member 4f3edc0cf8f1834e is healthy: got healthy result from https://10.0.219.231:2381\nmember 7fa5f87f2eb7b573 is healthy: got healthy result from https://10.0.127.250:2381\nmember 8489edc5f0c18d7a is unreachable: no available published client urls\nmember b434b32e55f3b651 is unreachable: no available published client urls\nmember e4bc01d02adbd8b6 is healthy: got healthy result from https://10.0.153.255:2381\ncluster is healthy", 
                "stdout_lines": [
                    "member 4f3edc0cf8f1834e is healthy: got healthy result from https://10.0.219.231:2381", 
                    "member 7fa5f87f2eb7b573 is healthy: got healthy result from https://10.0.127.250:2381", 
                    "member 8489edc5f0c18d7a is unreachable: no available published client urls", 
                    "member b434b32e55f3b651 is unreachable: no available published client urls", 
                    "member e4bc01d02adbd8b6 is healthy: got healthy result from https://10.0.153.255:2381", 
                    "cluster is healthy"
                ]
```

**Comment by davidewatson** [comment] 2017-08-03 03:17
From Slack, @mikeln reported: "anecdotally… it seems like 1.7.1 starts nodes sequentially, whereas before this version, nodes started pretty much simultaneously."

**Comment by davidewatson** [comment] 2017-08-03 03:18
Given the etcd health problem above, it is possible that this is a dupe of https://github.com/samsung-cnct/k2/issues/673.

**Comment by oneilcin** [comment] 2017-08-17 22:16
Doing a k2 image up.sh, none of the nodes passed readiness.  I logged into one of the master nodes and only kubelet is running.
Cynthias-MBP:~ cynthiaoneill$ kubectl get nodes
NAME                           STATUS     AGE       VERSION
ip-10-0-10-67.ec2.internal     NotReady   39m       v1.7.1
ip-10-0-124-176.ec2.internal   NotReady   39m       v1.7.1
ip-10-0-199-124.ec2.internal   NotReady   39m       v1.7.1
ip-10-0-21-147.ec2.internal    NotReady   40m       v1.7.1
ip-10-0-23-45.ec2.internal     NotReady   39m       v1.7.1
ip-10-0-252-214.ec2.internal   NotReady   39m       v1.7.1
ip-10-0-253-27.ec2.internal    NotReady   39m       v1.7.1
ip-10-0-255-171.ec2.internal   NotReady   39m       v1.7.1
ip-10-0-4-22.ec2.internal      NotReady   39m       v1.7.1
ip-10-0-63-95.ec2.internal     NotReady   39m       v1.7.1
ip-10-0-68-151.ec2.internal    NotReady   38m       v1.7.1
ip-10-0-71-48.ec2.internal     NotReady   39m       v1.7.1
ip-10-0-72-49.ec2.internal     NotReady   39m       v1.7.1
ip-10-0-74-140.ec2.internal    NotReady   28m       v1.7.1
ip-10-0-8-205.ec2.internal     NotReady   39m       v1.7.1

**Comment by davidewatson** [comment] 2017-08-17 23:04
This is a long running problem which we need to collect data on. If this occurs for you, please report any information you find here. Some interesting data includes the results of, `k get pods --all-namespaces`, `k get nodes`, for any pod/node which is not ready, `k describe [pod|node] $NAME`, and `k logs $POD_NAME`. You may also verify the status of etcd by running:

```
ssh -F ~/.kraken/dew/ssh_config etcd-1 etcdctl --ca-file=/etc/etcd/ssl/client-ca.pem --cert-file=/etc/etcd/ssl/client.pem --key-file=/etc/etcd/ssl/client-key.pem --endpoints=https://127.0.0.1:2379 cluster-health
```

For a working cluster you can expect something similar to:

```bash
rodin:k2 dwat$ k get pods --all-namespaces
NAMESPACE         NAME                                                   READY     STATUS    RESTARTS   AGE
kube-networking   canal-0gq0n                                            3/3       Running   0          49m
kube-networking   canal-0m9bd                                            3/3       Running   0          49m
kube-networking   canal-0mfvw                                            3/3       Running   0          49m
kube-networking   canal-3ftpn                                            3/3       Running   0          49m
kube-networking   canal-3pr1h                                            3/3       Running   0          49m
kube-networking   canal-3vmqr                                            3/3       Running   0          49m
kube-networking   canal-5wd36                                            3/3       Running   0          49m
kube-networking   canal-6hlnt                                            3/3       Running   0          49m
kube-networking   canal-80n6w                                            3/3       Running   0          49m
kube-networking   canal-gl85h                                            3/3       Running   0          49m
kube-networking   canal-hf1w7                                            3/3       Running   0          49m
kube-networking   canal-jfvmg                                            3/3       Running   0          49m
kube-networking   canal-njw9r                                            3/3       Running   0          49m
kube-networking   canal-p396f                                            3/3       Running   0          49m
kube-networking   canal-x8x0c                                            3/3       Running   0          49m
kube-system       heapster-standalone-2659379846-tt9lm                   2/2       Running   0          48m
kube-system       kube-apiserver-ip-10-0-134-225.ec2.internal            1/1       Running   0          48m
kube-system       kube-apiserver-ip-10-0-38-49.ec2.internal              1/1       Running   0          53m
kube-system       kube-apiserver-ip-10-0-95-106.ec2.internal             1/1       Running   0          48m
kube-system       kube-controller-manager-ip-10-0-134-225.ec2.internal   1/1       Running   0          48m
kube-system       kube-controller-manager-ip-10-0-38-49.ec2.internal     1/1       Running   0          54m
kube-system       kube-controller-manager-ip-10-0-95-106.ec2.internal    1/1       Running   0          48m
kube-system       kube-dns-3943270768-d0mwg                              3/3       Running   0          49m
kube-system       kube-proxy-ip-10-0-101-90.ec2.internal                 1/1       Running   0          53m
kube-system       kube-proxy-ip-10-0-123-255.ec2.internal                1/1       Running   0          54m
kube-system       kube-proxy-ip-10-0-123-99.ec2.internal                 1/1       Running   0          54m
kube-system       kube-proxy-ip-10-0-134-225.ec2.internal                1/1       Running   0          48m
kube-system       kube-proxy-ip-10-0-135-158.ec2.internal                1/1       Running   0          49m
kube-system       kube-proxy-ip-10-0-137-94.ec2.internal                 1/1       Running   0          53m
kube-system       kube-proxy-ip-10-0-16-17.ec2.internal                  1/1       Running   0          54m
kube-system       kube-proxy-ip-10-0-181-126.ec2.internal                1/1       Running   0          51m
kube-system       kube-proxy-ip-10-0-2-249.ec2.internal                  1/1       Running   0          54m
kube-system       kube-proxy-ip-10-0-214-51.ec2.internal                 1/1       Running   0          50m
kube-system       kube-proxy-ip-10-0-230-149.ec2.internal                1/1       Running   0          51m
kube-system       kube-proxy-ip-10-0-38-49.ec2.internal                  1/1       Running   0          53m
kube-system       kube-proxy-ip-10-0-43-3.ec2.internal                   1/1       Running   0          53m
kube-system       kube-proxy-ip-10-0-54-161.ec2.internal                 1/1       Running   0          53m
kube-system       kube-proxy-ip-10-0-95-106.ec2.internal                 1/1       Running   0          48m
kube-system       kube-scheduler-ip-10-0-134-225.ec2.internal            1/1       Running   0          48m
kube-system       kube-scheduler-ip-10-0-38-49.ec2.internal              1/1       Running   0          54m
kube-system       kube-scheduler-ip-10-0-95-106.ec2.internal             1/1       Running   0          48m
kube-system       tiller-deploy-3360264398-334fs                         1/1       Running   0          49m
rodin:k2 dwat$ k get nodes
NAME                           STATUS    AGE
ip-10-0-101-90.ec2.internal    Ready     54m
ip-10-0-123-255.ec2.internal   Ready     54m
ip-10-0-123-99.ec2.internal    Ready     54m
ip-10-0-134-225.ec2.internal   Ready     49m
ip-10-0-135-158.ec2.internal   Ready     50m
ip-10-0-137-94.ec2.internal    Ready     54m
ip-10-0-16-17.ec2.internal     Ready     54m
ip-10-0-181-126.ec2.internal   Ready     51m
ip-10-0-2-249.ec2.internal     Ready     54m
ip-10-0-214-51.ec2.internal    Ready     50m
ip-10-0-230-149.ec2.internal   Ready     51m
ip-10-0-38-49.ec2.internal     Ready     55m
ip-10-0-43-3.ec2.internal      Ready     54m
ip-10-0-54-161.ec2.internal    Ready     54m
ip-10-0-95-106.ec2.internal    Ready     54m
rodin:k2 dwat$ 
```

**Comment by oneilcin** [comment] 2017-08-18 22:07
Using the k2 image, with up.sh and for 8 consistent times I get nodes all NotReady.  I checked etcd health and looks like one node is not healthy.  I cleared cache (rm -rf ~/.kube/cache/discovery/*) still no luck.  Here are some stats:
Cynthias-MBP:~ cynthiaoneill$ kubectl get nodes
NAME                           STATUS     AGE       VERSION
ip-10-0-101-78.ec2.internal    NotReady   13m       v1.7.1
ip-10-0-11-26.ec2.internal     NotReady   19m       v1.7.1
ip-10-0-116-231.ec2.internal   NotReady   18m       v1.7.1
ip-10-0-119-156.ec2.internal   NotReady   19m       v1.7.1
ip-10-0-14-251.ec2.internal    NotReady   19m       v1.7.1
ip-10-0-151-228.ec2.internal   NotReady   16m       v1.7.1
ip-10-0-178-228.ec2.internal   NotReady   18m       v1.7.1
ip-10-0-179-203.ec2.internal   NotReady   19m       v1.7.1
ip-10-0-222-124.ec2.internal   NotReady   16m       v1.7.1
ip-10-0-25-133.ec2.internal    NotReady   19m       v1.7.1
ip-10-0-42-135.ec2.internal    NotReady   19m       v1.7.1
ip-10-0-44-31.ec2.internal     NotReady   19m       v1.7.1
ip-10-0-49-208.ec2.internal    NotReady   20m       v1.7.1
ip-10-0-66-140.ec2.internal    NotReady   19m       v1.7.1
ip-10-0-98-18.ec2.internal     NotReady   19m       v1.7.1

Cynthias-MBP:~ cynthiaoneill$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                   READY     STATUS    RESTARTS   AGE
kube-system   kube-apiserver-ip-10-0-116-231.ec2.internal            1/1       Running   0          18m
kube-system   kube-apiserver-ip-10-0-178-228.ec2.internal            1/1       Running   0          18m
kube-system   kube-apiserver-ip-10-0-49-208.ec2.internal             1/1       Running   0          19m
kube-system   kube-controller-manager-ip-10-0-116-231.ec2.internal   1/1       Running   0          18m
kube-system   kube-controller-manager-ip-10-0-178-228.ec2.internal   1/1       Running   0          17m
kube-system   kube-controller-manager-ip-10-0-49-208.ec2.internal    1/1       Running   0          19m
kube-system   kube-proxy-ip-10-0-101-78.ec2.internal                 1/1       Running   0          14m
kube-system   kube-proxy-ip-10-0-11-26.ec2.internal                  1/1       Running   0          19m
kube-system   kube-proxy-ip-10-0-116-231.ec2.internal                1/1       Running   0          18m
kube-system   kube-proxy-ip-10-0-119-156.ec2.internal                1/1       Running   0          20m
kube-system   kube-proxy-ip-10-0-14-251.ec2.internal                 1/1       Running   0          19m
kube-system   kube-proxy-ip-10-0-151-228.ec2.internal                1/1       Running   0          16m
kube-system   kube-proxy-ip-10-0-178-228.ec2.internal                1/1       Running   0          17m
kube-system   kube-proxy-ip-10-0-179-203.ec2.internal                1/1       Running   0          20m
kube-system   kube-proxy-ip-10-0-222-124.ec2.internal                1/1       Running   0          16m
kube-system   kube-proxy-ip-10-0-25-133.ec2.internal                 1/1       Running   0          20m
kube-system   kube-proxy-ip-10-0-42-135.ec2.internal                 1/1       Running   0          20m
kube-system   kube-proxy-ip-10-0-44-31.ec2.internal                  1/1       Running   0          19m
kube-system   kube-proxy-ip-10-0-49-208.ec2.internal                 1/1       Running   0          19m
kube-system   kube-proxy-ip-10-0-66-140.ec2.internal                 1/1       Running   0          20m
kube-system   kube-proxy-ip-10-0-98-18.ec2.internal                  1/1       Running   0          19m
kube-system   kube-scheduler-ip-10-0-116-231.ec2.internal            1/1       Running   0          18m
kube-system   kube-scheduler-ip-10-0-178-228.ec2.internal            1/1       Running   0          17m
kube-system   kube-scheduler-ip-10-0-49-208.ec2.internal             1/1       Running   0          20m

seq 1 5 | xargs -n 1 -I {} ssh -F ~/.kraken/cindy1/ssh_config etcd-{} etcdctl --endpoint https://127.0.0.1:2379 --ca-file=/etc/etcd/ssl/peer-ca.pem --cert-file=/etc/etcd/ssl/peer.pem --key-file=/etc/etcd/ssl/peer-key.pem cluster-health
Warning: Permanently added 'ec2-34-205-75-254.compute-1.amazonaws.com,34.205.75.254' (ECDSA) to the list of known hosts.
member 6cf8d3228bb89f98 is healthy: got healthy result from https://10.0.108.119:2379
member 6dba6a8686c8809f is healthy: got healthy result from https://10.0.248.177:2379
member 71886d9ea258e5dd is healthy: got healthy result from https://10.0.26.75:2379
member ccfdd97ba75770b3 is healthy: got healthy result from https://10.0.105.125:2379
member e3861ccbf343bc11 is healthy: got healthy result from https://10.0.193.49:2379
cluster is healthy
Warning: Permanently added 'ec2-54-173-63-235.compute-1.amazonaws.com,54.173.63.235' (ECDSA) to the list of known hosts.
member 6cf8d3228bb89f98 is healthy: got healthy result from https://10.0.108.119:2379
member 6dba6a8686c8809f is healthy: got healthy result from https://10.0.248.177:2379
member 71886d9ea258e5dd is healthy: got healthy result from https://10.0.26.75:2379
member ccfdd97ba75770b3 is healthy: got healthy result from https://10.0.105.125:2379
member e3861ccbf343bc11 is healthy: got healthy result from https://10.0.193.49:2379
cluster is healthy
Warning: Permanently added 'ec2-54-236-207-239.compute-1.amazonaws.com,54.236.207.239' (ECDSA) to the list of known hosts.
member 6cf8d3228bb89f98 is healthy: got healthy result from https://10.0.108.119:2379
member 6dba6a8686c8809f is healthy: got healthy result from https://10.0.248.177:2379
member 71886d9ea258e5dd is healthy: got healthy result from https://10.0.26.75:2379
member ccfdd97ba75770b3 is healthy: got healthy result from https://10.0.105.125:2379
member e3861ccbf343bc11 is healthy: got healthy result from https://10.0.193.49:2379
cluster is healthy
Warning: Permanently added 'ec2-54-85-169-197.compute-1.amazonaws.com,54.85.169.197' (ECDSA) to the list of known hosts.
member 6cf8d3228bb89f98 is healthy: got healthy result from https://10.0.108.119:2379
member 6dba6a8686c8809f is healthy: got healthy result from https://10.0.248.177:2379
member 71886d9ea258e5dd is healthy: got healthy result from https://10.0.26.75:2379
member ccfdd97ba75770b3 is healthy: got healthy result from https://10.0.105.125:2379
member e3861ccbf343bc11 is healthy: got healthy result from https://10.0.193.49:2379
cluster is healthy
ssh_exchange_identification: Connection closed by remote host
xargs: ssh: exited with status 255; aborting

Note: Sam is seeing a similar problem.  He always finds one bad etcd node.

**Comment by davidewatson** [comment] 2017-08-18 23:14
@oneilcin: The etcd status you posted suggests that the etcd cluster is healthy. Note that you only need to run `etcdctl cluster-health` on one instance in each etcd cluster. The reason we were looping over all instances before is that `etcdctl` used to return 0 when there were failed members but the cluster still had a quorum. As of etcd version 3.2.5, this is no longer the case.

If this happens again, can you log on to one of the clusterNodes and check on the kubelet using `curl -L http://127.0.0.1:10250/healthz` and `journalctl -u kubelet`?

**Comment by davidewatson** [comment] 2017-09-12 19:34
There have been no updates to this ticket in 25 days. Move to close.

**Comment by coffeepac** [comment] 2017-09-13 16:05
Id like to leave it another week.  Most of the past 25 days were cka time sink so no one has been working.  

If this remains without further input in a week im in for closing it.

**Closed** 2017-09-27 20:06 UTC
Labels: bug, kraken-lib, priority-p1
